import type { Metadata } from "next";
import { Montserrat, Merriweather, Montez } from "next/font/google";
import ApolloWrapper from '@/components/ApolloWrapper';
import {AuthProvider} from "@/contexts/VisitorAuthContext";

import "./globals.css";

import PageTransition from "@/components/PageTransition";


const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat",
});

const merriweather = Merriweather({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
  variable: "--font-merriweather",
});

const montez = Montez({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-montez",
});

export const metadata: Metadata = {
  title: "Say I Do",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
   
        <link rel="icon" href="/favicon.ico" />
      
      <body
        className={`${montserrat.variable} ${merriweather.variable} ${montez.variable}`}
      >
      <ApolloWrapper>
        {/* Wrapping the application with VisitorProvider */}
        <AuthProvider>
          {/* PageTransition can wrap around the children to handle animations */}
          <PageTransition>
            {children}
          </PageTransition>
        </AuthProvider>
      </ApolloWrapper>
        
      </body>
    </html>
  );
}
