FROM node:18.19.1

# Set the working directory
WORKDIR /app

COPY package*.json ./

RUN npm install

RUN chmod +x node_modules/.bin/eslint node_modules/.bin/jest node_modules/.bin/nest

COPY . .

RUN npm run build

EXPOSE 4000

CMD ["node", "dist/main.js"]
