FROM node:18.19.1

# Set the working directory
WORKDIR /app

COPY package*.json ./

RUN npm install -g @nestjs/cli

RUN npm install

COPY . .

RUN npm run build

EXPOSE 4000

CMD ["node", "dist/main.js"]
